/**
 * Author: DuongHan
 * Created: 4/3/19
 *
 */

// Picture Type
export const PICTURE_TYPE_REQUEST = 'PICTURE_TYPE_REQUEST';
export const FETCH_PICTURE_TYPE_SUCCESS = 'FETCH_PICTURE_TYPE_SUCCESS';
export const FETCH_PICTURE_TYPE_FAILED = 'FETCH_PICTURE_TYPE_FAILED';
export const SET_PICTURE_TYPE_LIST = 'SET_PICTURE_TYPE_LIST';
